protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
        /**
         * Controller default action, bruttó bér visszafejtése (1. feladat)
         */
	public function actionIndex()
	{
            $this->render('salary',array('data'=>$this->salaryCalculator('Falusi András', 458000)));
	}
        /**
         * Visszaadja egy asszociatív tömbben a bruttó fizetés járulékait (1. feladat)
         * 
         * @param string $name
         * @param int $brutto
         * @return array
         */
        protected function salaryCalculator($name, $brutto) {
            if (!is_numeric($brutto)) {$brutto = 0;}
            $result = array(
                $name, // Név
                $brutto // Bruttó
            );
            array_push(
                $result,
                $brutto * 0.16, // SZJA
                $brutto * 0.1, // Nyugdíj járulék
                $brutto * 0.085, // Egészségügyi hozzájárulás
                $brutto * (1 - (0.16 + 0.1 + 0.085)) // Nettó
            );
            $headers = array('Név', 'Bruttó', 'SZJA', 'Nyugdíj járulék', 'Egészségügyi hozzájárulás', 'Nettó bér');
            return array_combine($headers, $result);
        }

        /**
         * Controller action Array (3. feladat)
         */
        public function actionArray()
	{
            $array1 = array(97, 154, 66, 75, 122, 13254, 11, 0, 14);
            $array2 = array("A" => "Audi", "Z" => "BMW z4", "F" => "LaFerrari", "H" => "Hummer h2", "C" => "Corvette", "VW" => "VolksWagen Scirocco");
            $array3 = array("kutya", "alma", "macska", "hangya", "pocak", "nadrag", "golyostoll", "cekla", "korte", "angyal", "aaa2545", 14, 26, 48);
            $array4 = array (1.25, 63.44, 24.89, 6565.233331, 454, 1099, 6547);
            $dataProvider = new CArrayDataProvider(
                $this->processArrays($array1, $array2, $array3, $array4),
                array(
                    'keyField' => 'base',
                    'sort'=>array(
                        'attributes'=>array('base', 'sorted', 'sum', 'avg'),
                        'defaultOrder'=>array('base' => false),
                ),
            ));
            $this->render('array',array('data'=>$dataProvider));
	}

        /**
         * Tömbműveleteket végző függvény (3. feladat)
         * 
         * @param array $array1
         * @param array $array2
         * @param array $array3
         * @param array $array4
         * @return array
         */
        protected function processArrays($array1, $array2, $array3, $array4) {
            $arrays = array();
            for ($i = 1; $i <= 4; $i++) {
                $arrayName = 'array'.$i;
                $currentArray = $$arrayName;
                if (!is_array($currentArray)) {
                    continue;
                }
                $subArray = array();
                $subArray['base'] = implode(', ', $currentArray);
                asort($currentArray);
                $subArray['sorted'] = implode(', ', $currentArray);
                $subArray['sum'] = (array_sum($currentArray) > 0) ? array_sum($currentArray) : 'N/A';
                $subArray['avg'] = ($this->arrayLookup($currentArray)) ? array_sum($currentArray) / count($currentArray) : 'N/A';
                $arrays[] = $subArray;
            }
            return $arrays;
        }
        /**
         * Segédfüggvény mely egy tömbről megállapítja, hogy csak szám van-e benne vagy sem. (3. feladat)
         * 
         * @param array $array
         * @return boolean
         */
        protected function arrayLookup($array) {
            if (!is_array($array)) {return false;}
            foreach ($array as $item) {
                if (!is_numeric($item))
                    return false;
            }
            return true;
        }

        /**
         * Controller action Concat (4. feladat)
         */
        public function actionConcat() {
            $array = array('lajos', 'kiraly', 'pista', 'aladar', 'jozsef');
            $leftOver = '';
            $odd = array();
            $even = array();
            $both = array(&$even, &$odd);
            array_walk($array, function($v, $k) use ($both) { $both[$k % 2][] = $v; });
            if (count($even) != count($odd)) {
                $leftOver = '['.array_pop($even).']';
            }
            $even = implode('_', $even);
            $odd = implode('_', $odd);
            $this->render(
                'concat',
                array(
                    'even' => $even,
                    'odd' => $odd,
                    'leftOver' => $leftOver
                )
            );
        }

        /**
	 * Controller action Weather (5. és 6. feladat)
	 */
	public function actionWeather()
	{
            $model=new WeatherForm;
            $woeid = Yii::app()->request->getParam('woeid');
            if ($woeid && preg_match('|^\d+$|', $woeid)) {
                $model->curlWeather($woeid);
            } else {
                // if it is ajax validation request
                if(isset($_POST['ajax']) && $_POST['ajax']==='weather-form')
                {
                        echo CActiveForm::validate($model);
                        Yii::app()->end();
                }

                // collect user input data
                if(isset($_POST['WeatherForm']))
                {
                        $model->attributes=$_POST['WeatherForm'];
                        // validate user input and redirect to the previous page if valid
                        $model->curlPlaces();
                }
            }
            $this->render('weather',array('model'=>$model));
	}

        /**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
}

protected/controllers/SortController.php
<?php

class SortController extends Controller
{
	/**
	 * Controller default action, csak azért raktam külön controllerbe, mert a feladat kimondja. (2. feladat)
	 */
	public function actionIndex()
	{
            $array = array(
                'Kiss Janos' => 170000,
                'Nagy Jozsef' => 198500,
                'Szegeny Bela' => 2500000,
                'Magnas Miska' => 750000,
                'Gipsz Jakab' => 458010
            );
            $this->convertData($array);
            $dataProvider = new CArrayDataProvider(
                $array,
                array(
                    'keyField' => 'nev',
                    'sort'=>array(
                        'attributes'=>array('nev', 'netto'),
                        'defaultOrder'=>array('netto' => true),
                ),
            ));
            $this->render('salarysort',array('data'=>$dataProvider));
	}

        /**
         * Átalakító függvény ami a CArrayDataProvider osztály számára értelmezhető formába hozza a tömböt
         * 
         * @param array $array
         * @return array
         */
        protected function convertData(&$array) {
            if (!is_array($array))
            {
                return array();
            } else {
                array_walk($array, array('SortController', 'convertRow'));
                $array = array_values($array);
            }
        }
        /**
         * Segédfüggvény convertData függvényhez
         * 
         * @param type $row
         * @param type $key
         */
        protected function convertRow(&$row, $key) {
            $row = array('nev' => $key, 'netto' => $row);
        }

        /**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
 }

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="language" content="en">

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'1.) feladat', 'url'=>array('/site/index')),
				array('label'=>'2.) feladat', 'url'=>array('/sort/index')),
				array('label'=>'3.) feladat', 'url'=>array('/site/array')),
				array('label'=>'4.) feladat', 'url'=>array('/site/concat')),
				array('label'=>'5.) és 6.) feladat', 'url'=>array('/site/weather')),
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		&copy; <?php echo date('Y'); ?> Falusi András<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>